### PR TITLE
Created functions to get files changed in a dataset after a specific date, and also to upload various files into a CKAN package easily

### PR DESCRIPTION
**Pull request by NelsonPereira1991**
This code is based on this pull request https://github.com/okfn/ckan.js/pull/24, although the scraping of the api token was removed as requested by @rufuspollock 

1- Is there any reason why every action that starts with "dataset_" is replaced with "package_" ? 

I wrote some automated tests for our platform [Dendro](https://github.com/feup-infolab/dendro) that test package exporting from Dendro to CKAN instances. The tests run very frequently and are always creating new packages, so after each test I would like to purge them by calling the action ["dataset_purge"](http://docs.ckan.org/en/ckan-2.7.0/api/#ckan.logic.action.delete.dataset_purge). To do this, I had to change some code in ckan.js, as I noticed that you are replacing every action (my.Client.prototype.action) that starts with "dataset_" with "package_". 

Before (maybe a bug, because the parenthesis in the if are not closed at the right place, as the comparison is always false):
````
    if (name.indexOf('dataset_' === 0)) {
      name = name.replace('dataset_', 'package_');
    }
````

After:
````
  my.Client.prototype.action = function(name, data, cb) {
    if (name !== "dataset_purge" && name.indexOf('dataset_') === 0) {
      name = name.replace('dataset_', 'package_');
    }
````

2- We added a function getChangesInDatasetAfterDate which calculates the resources changed in CKAN after a given date, something very simple but likely boilerplate code in others using ckan.js. It was useful to us at Dendro to warn Dendro users that changes were or not made on the package on the CKAN side so we thought it would be a useful contribution for this pull request. It may be useful in similar scenarios, where: 1. one makes a deposit in CKAN through an external client, 2. updates the original data in CKAN and then tries to "refresh" the dataset deposited in CKAN via the said client. We figured that users would like to be warned before potentially destroying something that was meanwhile done on the CKAN side.

3- Would you be interested in a function that given an array of objects ( with properties filepath, file metadata and fileID) would update the full package in Ckan ? This is useful in scenarios where a client that exports datasets to CKAN needs to keep track of those deposited datasets and allow for subsequent updates (much like mentioned in the previous point). Such a function allows the client to easily refresh the files and metadata in CKAN if any files or metadata is updated in the client. We have already implemented this for Dendro but we believe it can be useful to other CKAN users and platforms where data is dynamic.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@loleg would you be interested in reviewing this?

**Comment by loleg** [comment]
Yes.

**Comment by rufuspollock** [comment]
@loleg **great** 👍 💯 PR review. Thank-you. I think it is unlikely this get merged as is based on your feedback (and would in fact be happy to make you the arbiter of that).

My sense, given the marginal value of the main feature here, that it live separately either in a separate repo (which we can point to in the README) or in an "examples" directory here. My preference is for the former as it keeps this repo lightweight.

Of course, any bug fixes or ES6 upgrades are very welcome in this repo.

**Comment by silvae86** [comment]
Dear @loleg and @rufuspollock ,

First of all, thank you for your detailed and comprehensive code review. We understand your points and will try to move the functionality to a separate npm module, which we will call ckan-sync.js. 

This name derives from the functionality of this pull request, which is to keep datasets in external systems synchronised with its ckan-deposited counterparts. This, of course, includes batch upload of files to keep both data and metadata synchronised. If you have a suggestion for a different name, we would be glad to hear it.

We do agree that having a method that can cause data loss is undesirable, but the need for such a method arose from the need for automated testing. Without a purge method, our CKAN test instance would be bloated with garbage datasets that we kept deleting and recreating. Maybe for inclusion in the `ckan.js` it should be harder to invoke somehow, so that any developers using it would not call the method by mistake (i.e. adding an optional flag with a "scandalous" name like "I_REALLY_WANT_TO_PURGE" or at least warn the developers wanting to execute a purge action that it is unsafe and will result in data loss).

As you point out, we should move the bloat of the new dependencies in our module not to encumber the main `ckan.js` module and keep it client-server cross-compatible. Also, the introduction of ES6 should be complete and not piecemeal, so we will make our module fully ES6-compliant, and ckan.js will remain ES5 (which will not require other users of `ckan.js` to upgrade their NodeJS versions, for example). In the future we can work on migrating the ckan.js module to ES6 as @rufuspollock pointed out.

We will also create a new pull request, fixing only the `name.indexOf('dataset_' === 0)` bug.

After we build this new `ckan-sync.js` module we will let you know, and if you could review it and mention it in your README, we would appreciate it. 

We plan to include full test coverage in this new module as well, using the mocha framework. For CI integration, we will use Travis and our own CKAN dummy instance, where we can issue purge commands at will. 

Thank you very much,
João & Nelson

**Comment by loleg** [comment]
It looks like this module was created here: https://github.com/feup-infolab/ckan-sync.js

**Comment by rufuspollock** [comment]
WONTFIX. based on feedback above. Welcome a PR to readme linking to the separate project 😄

**Pull request closed without merging**
