### PR TITLE
Updates for webpack 3?

### PR DESCRIPTION
**Pull request by not-a-designer**
This is my first time trying this so let me know if i am understanding correctly

but i just updated the 'request' package to now be 'superagent'

is that the fix for webpack 3 compatibility?

### CODE REVIEW

**Comment by rufuspollock** [comment]
Thanks for the PR. Could you give a bit more info on the motivation for this change?

**Comment by not-a-designer** [comment]
I was trying to use the ckan package with my Angular (7+) application to access some OpenData dot gov information. I had run into some similar issues with some older stable packages that have dependencies that are different or built into webpack 3 now. Again, I am a bit out of my depth here as an end user, but I think that is whats

**Comment by rufuspollock** [comment]
@not-a-designer ok - i'm going to close this for now as it seems a bit incomplete.

**Comment by loleg** [comment]
@not-a-designer I tested that library as well as bent.js, and decided to go with needle as per #34

**Pull request closed without merging**
